# Generated by Django 4.1.2 on 2022-10-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Articles',
        ),
    ]
